<a href="https://colab.research.google.com/github/souma21122002/DeepLearning/blob/main/Sonar_Single_Layer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

tf.compat.v1.disable_eager_execution()

In [3]:
df=pd.read_csv('/content/drive/MyDrive/ML/sonar.csv',header=None)
print(len(df.columns))

61


In [4]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

there are two classes 1.rock 2.mine(metal cylinder)

In [5]:
x=df[df.columns[0:60]].values  # x is assigned with 0 to 59th columns which are independent
y=df[df.columns[60]] # y is assigned with the dependent column which is 60th

x

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [6]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [7]:
y_labelencoder=LabelEncoder()
y=y_labelencoder.fit_transform(y.astype(str))  # converting the y column from string to numbers
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
y=y.reshape(-1,1)
onehotencoder=OneHotEncoder(categories='auto', sparse_output=False)
Y=onehotencoder.fit_transform(y)
Y # in the output if one belongs to rock then its 1 and other is 0 . so we got 2 separate classes

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [9]:
train_x,test_x,train_y,test_y=train_test_split(x,Y,test_size=0.20,random_state=42)
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(166, 60)
(166, 2)
(42, 60)
(42, 2)


In [10]:
learning_rate=0.01
training_epochs=100
cost_history=np.empty(shape=[1],dtype=float)

In [11]:
n_class=2 #rock and mine
X=tf.compat.v1.placeholder(tf.float32,[None,60]) # 60 columns
w=tf.Variable(tf.zeros([60,n_class])) # 60 size as input are 60s and 2 columns
b=tf.Variable(tf.zeros([n_class])) # 2 class

In [12]:
init=tf.compat.v1.global_variables_initializer()

In [13]:
y=tf.compat.v1.placeholder(tf.float32,[None,n_class]) #actual y
pred=tf.nn.softmax(tf.matmul(X,w)+b) # softmax is used for multiclass classification as an activation function

In [14]:
cost_function=tf.reduce_mean(-tf.reduce_sum(y*tf.math.log(pred))) # cost function calculating rmse

In [15]:
training_step=tf.compat.v1.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)

In [16]:
sess=tf.compat.v1.Session()
sess.run(init)
mse_history=[]

In [19]:
for i in range(100):
  sess.run(training_step,feed_dict={X:train_x,y:train_y})
  cost=sess.run(cost_function,feed_dict={X:train_x,y:train_y})
  cost_history=np.append(cost_history,cost) # storing the cost

  pred_y=sess.run(pred,feed_dict={X:test_x})
  print('epoch:',i,' - ','cost:' , cost)
  mse=tf.reduce_mean(tf.square(pred_y-test_y))
  mse_history.append(sess.run(mse))

epoch: 0  -  cost: 117.10057
epoch: 1  -  cost: 297.08432
epoch: 2  -  cost: 857.899
epoch: 3  -  cost: 253.21385
epoch: 4  -  cost: 838.7319
epoch: 5  -  cost: 253.43784
epoch: 6  -  cost: 820.82135
epoch: 7  -  cost: 253.01486
epoch: 8  -  cost: 799.34644
epoch: 9  -  cost: 256.63477
epoch: 10  -  cost: 776.82446
epoch: 11  -  cost: 261.66525
epoch: 12  -  cost: 752.83057
epoch: 13  -  cost: 268.38757
epoch: 14  -  cost: 727.96106
epoch: 15  -  cost: 276.00464
epoch: 16  -  cost: 702.34564
epoch: 17  -  cost: 284.08615
epoch: 18  -  cost: 676.3037
epoch: 19  -  cost: 291.92874
epoch: 20  -  cost: 650.1422
epoch: 21  -  cost: 298.91248
epoch: 22  -  cost: 624.2648
epoch: 23  -  cost: 304.65268
epoch: 24  -  cost: 599.09265
epoch: 25  -  cost: 309.12912
epoch: 26  -  cost: 574.98724
epoch: 27  -  cost: 312.50696
epoch: 28  -  cost: 552.17236
epoch: 29  -  cost: 314.8988
epoch: 30  -  cost: 530.7192
epoch: 31  -  cost: 316.25552
epoch: 32  -  cost: 510.59427
epoch: 33  -  cost: 316.5240