<a href="https://colab.research.google.com/github/souma21122002/DeepLearning/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.version.VERSION

'2.18.0'

In [ ]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

#building a computational graph
a=tf.constant(2)
b=tf.constant(4)
c=a+b
print(c)

Tensor("add_7:0", shape=(), dtype=int32)


In [ ]:
#running a computational graph
ssn=tf.compat.v1.Session()

ssn.run(c)

6

In [ ]:
x1=tf.constant([1,2,4,5])
x2=tf.constant([2,3,5,6])

result=tf.multiply(x1,x2)
print(result)
ssn.run(result)


Tensor("Mul_5:0", shape=(4,), dtype=int32)


array([ 2,  6, 20, 30], dtype=int32)

In [ ]:
result1=x1*x2
ssn.run(result1)

array([ 2,  6, 20, 30], dtype=int32)

**Placeholder**==giving the value at the time of execution

In [ ]:
a=tf.compat.v1.placeholder(tf.float32)
b=tf.compat.v1.placeholder(tf.float32)
c=a+b

In [ ]:
ssn.run(c,{a:1,b:3})

4.0

In [ ]:
ssn.run(c,{a:[1,3,4,5],b:[3,8,9,5]})

array([ 4., 11., 13., 10.], dtype=float32)

**Variable**

In [ ]:
x=tf.compat.v1.Variable([2])
w=tf.compat.v1.Variable([3])
c=x*w
init=tf.compat.v1.global_variables_initializer()
ssn.run(init)
ssn.run(c)

array([6], dtype=int32)